apiVersion: v1
kind: Service
metadata:
  name: java-rag-service
  namespace: default
  labels:
    app: java-rag-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-direct
  selector:
    app: java-rag-service
